# Use the official Caddy image as the base
FROM caddy:alpine

# Copy static files into the container
COPY . /usr/share/caddy

# Copy the Caddyfile to configure the server
# sCOPY Caddyfile /etc/caddy/Caddyfile

# Expose port 80 for the web server
EXPOSE 80
